// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ00OcqaVa98O7yqmPF1rVFwv5j1UwF14',
    appId: '1:252065816845:web:10117b307a03b5cacb5044',
    messagingSenderId: '252065816845',
    projectId: 'e-commerce-9d7cd',
    authDomain: 'e-commerce-9d7cd.firebaseapp.com',
    storageBucket: 'e-commerce-9d7cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATT27VLGGlb0wUk8SGNTGTUNQkpk2f_gk',
    appId: '1:252065816845:android:e6dc56f90efcc0e2cb5044',
    messagingSenderId: '252065816845',
    projectId: 'e-commerce-9d7cd',
    storageBucket: 'e-commerce-9d7cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu6bVlaIBq4wzvwhmu9Cdy3JYvnhEUhDc',
    appId: '1:252065816845:ios:9079778bd19dd568cb5044',
    messagingSenderId: '252065816845',
    projectId: 'e-commerce-9d7cd',
    storageBucket: 'e-commerce-9d7cd.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu6bVlaIBq4wzvwhmu9Cdy3JYvnhEUhDc',
    appId: '1:252065816845:ios:bd3eb67347212913cb5044',
    messagingSenderId: '252065816845',
    projectId: 'e-commerce-9d7cd',
    storageBucket: 'e-commerce-9d7cd.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
